"""PRISM v4.49: persistent evidence ingestion, PIT validation and bounded collection.
No historical catalyst scores without verified source timestamps.
"""
import argparse,hashlib,json,os,time,html
from pathlib import Path
import pandas as pd,requests
COLUMNS=["ticker","signal_date","source","source_url","headline","first_public_utc","observed_utc","pit_status","evidence_id"]
def main():
 p=argparse.ArgumentParser()
 p.add_argument("--targets",default="results/prism-v447/research_targets.csv")
 p.add_argument("--store",default="data-cache/prism-catalysts")
 p.add_argument("--out",default="results/prism-v449")
 p.add_argument("--ir-input",default="data/prism/ir_evidence_pit.csv")
 p.add_argument("--max-requests",type=int,default=5)
 p.add_argument("--collect",action="store_true")
 a=p.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True)
 store=Path(a.store);store.mkdir(parents=True,exist_ok=True)
 targets=pd.read_csv(a.targets)
 if not {"ticker","entry_date"}.issubset(targets):raise RuntimeError("Missing research target fields")
 targets.entry_date=pd.to_datetime(targets.entry_date).dt.normalize()
 # For conservative PIT gating use midnight UTC of entry date, not a guessed
 # previous signal close. A genuine signal timestamp is needed for promotion.
 targets["cutoff"]=targets.entry_date.dt.tz_localize("UTC")
 raw=[];errors=[];requests_made=0
 existing=store/"evidence.csv"
 if existing.exists():
  old=pd.read_csv(existing)
  if not set(COLUMNS).issubset(old):raise RuntimeError("Corrupt evidence cache")
  raw+=old[COLUMNS].to_dict("records")
 ir=Path(a.ir_input)
 if ir.exists():
  f=pd.read_csv(ir)
  if not {"ticker","signal_date","source_url","headline","first_public_utc"}.issubset(f):
   raise RuntimeError("IR source missing mandatory provenance fields")
  for r in f.itertuples(index=False):
   raw.append({"ticker":str(r.ticker),"signal_date":str(r.signal_date),"source":"CURATED_IR",
    "source_url":str(r.source_url),"headline":str(r.headline),"first_public_utc":str(r.first_public_utc),
    "observed_utc":"","pit_status":"UNVERIFIED","evidence_id":""})
 # Bounded, optional discovery; never retry 429 within the same job.
 if a.collect:
  session=requests.Session()
  session.headers.update({"User-Agent":os.getenv("SEC_USER_AGENT","PRISM-Research/1.0")})
  for r in targets.sort_values(["entry_date","ticker"]).drop_duplicates(["ticker","entry_date"]).itertuples(index=False):
   if requests_made>=a.max_requests:break
   requests_made+=1
   try:
    dt=pd.Timestamp(r.entry_date)
    response=session.get("https://api.gdeltproject.org/api/v2/doc/doc",
     params={"query":'"'+str(r.ticker)+'" (earnings OR guidance OR contract)',
      "mode":"artlist","format":"json","maxrecords":10,
      "startdatetime":(dt-pd.Timedelta(days=60)).strftime("%Y%m%d%H%M%S"),
      "enddatetime":dt.strftime("%Y%m%d%H%M%S")},timeout=20)
    if response.status_code==429:
     errors.append({"source":"GDELT","ticker":r.ticker,"status":429,"action":"STOP_RATE_LIMIT"})
     break
    response.raise_for_status()
    data=response.json()
    for item in data.get("articles",[]):
     if not item.get("url"):continue
     raw.append({"ticker":str(r.ticker),"signal_date":str(dt.date()),"source":"GDELT",
      "source_url":item["url"],"headline":item.get("title",""),
      "first_public_utc":"","observed_utc":item.get("seendate",""),
      "pit_status":"DISCOVERY_ONLY","evidence_id":""})
   except Exception as exc:
    errors.append({"source":"GDELT","ticker":r.ticker,"error":str(exc)})
   time.sleep(2)
 # SEC evidence can be imported from verified metadata generated by a separate
 # acquisition environment. No SEC live requests are made by this workflow.
 secfile=store/"sec_import.csv"
 if secfile.exists():
  sec=pd.read_csv(secfile)
  needed={"ticker","entry_date","source_url","acceptance_utc","accession"}
  if not needed.issubset(sec):raise RuntimeError("SEC import missing provenance")
  for r in sec.itertuples(index=False):
   raw.append({"ticker":str(r.ticker),"signal_date":str(r.entry_date),"source":"SEC",
    "source_url":str(r.source_url),"headline":"SEC filing "+str(r.accession),
    "first_public_utc":str(r.acceptance_utc),"observed_utc":"",
    "pit_status":"METADATA_VERIFIED","evidence_id":""})
 df=pd.DataFrame(raw,columns=COLUMNS)
 if len(df):
  df["evidence_id"]=[hashlib.sha256((str(r.ticker)+"|"+str(r.source_url)+"|"+str(r.signal_date)).encode()).hexdigest()[:20] for r in df.itertuples(index=False)]
  df=df.drop_duplicates("evidence_id",keep="last")
  df["first_ts"]=pd.to_datetime(df.first_public_utc,utc=True,errors="coerce")
  # Only verified SEC metadata can pass the timestamp gate automatically.
  df["cutoff"]=df.apply(lambda r:pd.Timestamp(str(r.signal_date)[:10]).tz_localize("UTC") if pd.notna(r.signal_date) else pd.NaT,axis=1)
  df["pit_eligible"]=(df.source=="SEC")&(df.pit_status=="METADATA_VERIFIED")&df.first_ts.notna()&(df.first_ts<df.cutoff)
  df["pit_status"]=df.pit_status.where(~((df.source=="SEC")&~df.pit_eligible),"TIMESTAMP_INVALID")
  df[COLUMNS].to_csv(existing,index=False)
  df.to_csv(out/"evidence_audit.csv",index=False)
 else:
  pd.DataFrame(columns=COLUMNS).to_csv(existing,index=False)
  pd.DataFrame(columns=COLUMNS+["pit_eligible"]).to_csv(out/"evidence_audit.csv",index=False)
 (out/"source_errors.json").write_text(json.dumps(errors,ensure_ascii=False,indent=2))
 report={"version":"v4.49","status":"EVIDENCE_INFRASTRUCTURE_ONLY",
  "targets":len(targets),"stored_records":len(df),
  "sec_metadata_pit_eligible":int(df.pit_eligible.sum()) if len(df) else 0,
  "requests_made":requests_made,"source_errors":len(errors),
  "catalyst_scores":0,"investment_backtest":"NOT_RUN",
  "limitations":["SEC live requests disabled; SEC imports must be independently acquired and provenance-checked.",
   "GDELT discovery is rate limited and never auto-certified as first-public-time.",
   "Cached records persist only if GitHub cache restores successfully; downloadable artifacts are also uploaded.",
   "Entry-date midnight is conservative and not a substitute for verified signal-close timestamps.",
   "Filing metadata verification does not imply catalyst polarity or magnitude.",
   "No returns are attributed to unavailable or unverified catalyst evidence."]}
 (out/"summary.json").write_text(json.dumps(report,ensure_ascii=False,indent=2))
 (out/"report.html").write_text("<!doctype html><meta charset='utf-8'><title>PRISM v4.49</title><style>body{background:#0b1729;color:#eaf4ff;font:15px system-ui;margin:28px}h1{color:#5de4bd}pre{white-space:pre-wrap}</style><h1>PRISM v4.49 · Evidence Infrastructure</h1><pre>"+html.escape(json.dumps(report,ensure_ascii=False,indent=2))+"</pre>",encoding="utf-8")
 print(json.dumps(report,ensure_ascii=False))
if __name__=="__main__":main()
